[package]
name = "cargo-depbuilder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
execute = "0.2.11"
regex = "1.6.0"
indexmap = "1.9.1"
